name: Gradle Package
on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Create archive with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: archive
        
    - name: Publish to GitHub Packages
      run: |
        gh release create Release-${GITHUB_REF_NAME} build/dist/evolven-cli.zip --latest --title ${GITHUB_REF_NAME} --notes "Release ${GITHUB_REF_NAME}"
      env:
        GH_TOKEN: ${{ github.token }}
